# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2
# Define environment variables for production deployment
env_variables:
  SPRING_PROFILES_ACTIVE: cloud
